version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - 27017:27017

  publisher:
    build:
      context: .
      dockerfile: Dockerfile.publisher
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
      KAFKA_TOPIC: test-topic
    depends_on:
      - kafka
    ports:
      - 8000:8000

  subscribers:
    build:
      context: .
      dockerfile: Dockerfile.subscriber
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
      KAFKA_TOPIC: test-topic
      MONGO_URI: mongodb://mongo:27017
    depends_on:
      - kafka
      - mongo
    ports:
      - 8001:8001
      - 8002:8002
